### ISSUE TITLE
Where is the source code of the core programm of geodesk?

### ISSUE THREAD

**Issue by stephan75** [clarisma/geodesk-site#1]
hello @clarisma  ... Maybe my searching was not deep enough, but:

Where is the source code of the core programm of geodesk?

Only docs and website (old and new?) are available on github so far?

**Comment by clarisma** [comment]
Hi, thanks for checking out our project!
We're still in beta, we're planning to make the project repositories public in about a week or two.
You can follow this issue (or @GeoDeskTeam on Twitter) and we'll notify once we're going live.
Did you find our site via the OSM Wiki?

**Comment by stephan75** [comment]
Yes, its has drawn my attention when browsing the recent changes feature of the OSM wiki.

Additionally I started a little topic in the new OSM forum, German sub community there.
Some others pointed out that some links on your website have empty targets or similar, and also about the sourcecode.

Will try to watch the next weeks about progress with curiosity ;-)

**Comment by clarisma** [comment]
Hi @stephan75,

The following GitHub repositories are now public:

- [`clarisma/geodesk`](http://www.github/clarisma.com/geodesk): This is the principal repository for the GeoDesk database engine toolkit.

- [`clarisma/gol-tool`](http://www.github/clarisma.com/gol-tool): The `gol` command-line utility

- [`clarisma/geodesk-examples`](http://www.github.com/clarisma/geodesk-examples): Several small sample applications

- [`clarisma/geodesk-tests`](http://www.github.com/clarisma/geodesk-tests): Integration tests and benchmarks

We have not formally released yet; we expect to make an announcement shortly.

We've decided to designate our initial release as Early Access. We figured it would be more worthwhile to get it into the hands of the OSM community sooner, instead of waiting to ship it in a more polished form. Consequently, we've deferred some lower-priority features to Version 0.2, slated for Q1 2023.

There will be at least one maintenance release prior to year-end, to address any issues that will invariably crop up once the software runs on a broader variety of platforms. We've successfully tested on Windows 10 and Ubuntu Linux 20.04. GeoDesk is written in pure Java and does not rely on any platform-specific features, so any 64-bit OS for which a JVM is available should be suitable (It will not run on 32-bit hardware/OS/JVM).

The yellow tags in the [user guide](http://docs.geodesk.com) indicate the features that are not yet available, and the version for which they are targeted.

**GeoDesk GOL tool**: You can download the latest release candidate at https://github.com/clarisma/gol-tool/releases. The tool is stable, the open issues are mostly cosmetic, or minor options that are missing. Use it to build GOLs from `.osm.pbf` files, perform queries, and export OSM features in other formats (e.g. GeoJSON). See [`gol` user guide](http://docs.geodesk.com/gol)

You'll need the **GeoDesk Library** if you want to build your own geospatial applications. Once we officially release, it will be on Maven Central and hence downloaded automatically by Maven (Just add the `<dependency>` to your project's POM). In the meantime, you can build it from source and do a manual `mvn install` (see https://github.com/clarisma/geodesk#maven). For details, have a look at the [tutorial](http://docs.geodesk.com/tutorial) and [examples](http://www.github.com/clarisma/geodesk-examples).

Found a bug? Need help?

- View/submit [issues on GitHub](https://github.com/clarisma/geodesk/issues).

- For questions that may be of interest to non-developers (such as using the `gol` tool to convert OSM data to other formats), you can also open a discussion on [OpenStreetMap Community](https://community.openstreetmap.org/) and tag `@GeoDeskTeam`.

- To learn about our latest releases, follow [@GeoDeskTeam](https://twitter.com/GeoDeskTeam) on Twitter.

Happy querying!
